"""Pydantic response models for all 5 LLM pipeline stages."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------

class Severity(str, Enum):
    critical = "critical"
    major = "major"
    minor = "minor"
    enhancement = "enhancement"


class EmotionalState(str, Enum):
    confident = "confident"
    curious = "curious"
    neutral = "neutral"
    hesitant = "hesitant"
    confused = "confused"
    frustrated = "frustrated"
    satisfied = "satisfied"
    anxious = "anxious"


class ActionType(str, Enum):
    click = "click"
    type_text = "type"
    scroll = "scroll"
    navigate = "navigate"
    wait = "wait"
    go_back = "go_back"
    done = "done"
    give_up = "give_up"


class IssueType(str, Enum):
    ux = "ux"
    accessibility = "accessibility"
    error = "error"
    performance = "performance"


class FixLanguage(str, Enum):
    css = "css"
    html = "html"
    javascript = "javascript"
    react = "react"
    general = "general"


# ---------------------------------------------------------------------------
# Stage 1: Persona Generation
# ---------------------------------------------------------------------------

class AccessibilityNeeds(BaseModel):
    screen_reader: bool = False
    low_vision: bool = False
    color_blind: bool = False
    motor_impairment: bool = False
    cognitive: bool = False
    description: str | None = None


class PersonaProfile(BaseModel):
    """Full persona profile generated by Opus."""

    name: str = Field(..., description="Short descriptive archetype label (e.g. 'Visually Impaired Professor')")
    age: int = Field(..., ge=13, le=95)
    occupation: str
    emoji: str = Field(..., description="Single emoji avatar")
    short_description: str = Field(..., max_length=200)
    background: str = Field(..., description="2-3 sentence backstory")

    # Behavioral attributes (1-10 scale)
    tech_literacy: int = Field(..., ge=1, le=10)
    patience_level: int = Field(..., ge=1, le=10)
    reading_speed: int = Field(..., ge=1, le=10, description="1=skims, 10=reads every word")
    trust_level: int = Field(..., ge=1, le=10, description="1=very skeptical, 10=trusts everything")
    exploration_tendency: int = Field(..., ge=1, le=10, description="1=task-focused, 10=explores everything")

    # Context
    device_preference: str = Field(default="desktop", description="desktop, mobile, or tablet")
    frustration_triggers: list[str] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    accessibility_needs: AccessibilityNeeds = Field(default_factory=AccessibilityNeeds)

    # Behavioral modifiers derived from attributes
    behavioral_notes: str = Field(
        default="",
        description="Generated behavioral notes for the navigation engine",
    )


# ---------------------------------------------------------------------------
# Stage 2: Navigation Decision-Making
# ---------------------------------------------------------------------------

class NavigationAction(BaseModel):
    """A single browser action to execute."""

    type: ActionType
    selector: str | None = Field(None, description="CSS selector for click/type")
    value: str | None = Field(None, description="Text to type, URL to navigate, scroll direction")
    description: str = Field(..., description="Human-readable description of the action")


class UXIssue(BaseModel):
    """A UX issue detected during navigation."""

    element: str = Field(..., description="The UI element involved")
    description: str
    severity: Severity
    heuristic: str = Field(..., description="Nielsen heuristic violated")
    wcag_criterion: str | None = Field(None, description="WCAG criterion if applicable")
    recommendation: str
    issue_type: IssueType = Field(
        default=IssueType.ux,
        description="Category: ux, accessibility, error, or performance",
    )


class NavigationDecision(BaseModel):
    """Output of the navigation LLM call (Stage 2)."""

    think_aloud: str = Field(..., description="Persona's inner monologue / think-aloud")
    action: NavigationAction
    ux_issues: list[UXIssue] = Field(default_factory=list)
    confidence: float = Field(..., ge=0, le=1, description="Confidence in the chosen action")
    task_progress: int = Field(
        ..., ge=0, le=100, description="Estimated task completion percentage"
    )
    emotional_state: EmotionalState = Field(default=EmotionalState.neutral)
    reasoning: str = Field(default="", description="Internal reasoning for the action choice")


# ---------------------------------------------------------------------------
# Stage 3: Screenshot UX Analysis (post-session)
# ---------------------------------------------------------------------------

class PageAssessment(BaseModel):
    """Assessment scores for a single page screenshot."""

    visual_clarity: int = Field(..., ge=1, le=10)
    information_hierarchy: int = Field(..., ge=1, le=10)
    action_clarity: int = Field(..., ge=1, le=10)
    error_handling: int = Field(..., ge=1, le=10)
    accessibility: int = Field(..., ge=1, le=10)
    overall: int = Field(..., ge=1, le=10)


class ScreenshotAnalysis(BaseModel):
    """Output of the screenshot analysis LLM call (Stage 3)."""

    page_url: str
    page_title: str
    assessment: PageAssessment
    issues: list[UXIssue] = Field(default_factory=list)
    strengths: list[str] = Field(default_factory=list)
    summary: str


# ---------------------------------------------------------------------------
# Stage 4: Cross-Persona Insight Synthesis
# ---------------------------------------------------------------------------

class StrugglePoint(BaseModel):
    """A point in the flow where personas struggled."""

    page_url: str
    element: str | None = None
    description: str
    personas_affected: list[str] = Field(default_factory=list)
    severity: Severity


class Recommendation(BaseModel):
    """A prioritized recommendation."""

    rank: int
    title: str
    description: str
    impact: str = Field(..., description="high, medium, or low")
    effort: str = Field(..., description="high, medium, or low")
    personas_helped: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)


class InsightItem(BaseModel):
    """A single insight from synthesis."""

    type: str = Field(
        ..., description="universal, persona_specific, comparative, or recommendation"
    )
    title: str
    description: str
    severity: Severity
    personas_affected: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)
    reasoning_trace: str = Field(default="", description="Opus extended thinking trace for this insight")


class StudySynthesis(BaseModel):
    """Output of the cross-persona synthesis LLM call (Stage 4)."""

    executive_summary: str
    overall_ux_score: int = Field(default=50, ge=0, le=100)
    reasoning_trace: str = Field(default="", description="Full Opus extended thinking trace for synthesis")
    universal_issues: list[InsightItem] = Field(default_factory=list)
    persona_specific_issues: list[InsightItem] = Field(default_factory=list)
    comparative_insights: list[InsightItem] = Field(default_factory=list)
    struggle_points: list[StrugglePoint] = Field(default_factory=list)
    recommendations: list[Recommendation] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Stage 5: Report Generation
# ---------------------------------------------------------------------------

class ReportSection(BaseModel):
    """A section of the generated report."""

    heading: str
    content: str = Field(..., description="Markdown content")
    subsections: list[ReportSection] = Field(default_factory=list)


class ReportContent(BaseModel):
    """Output of the report generation LLM call (Stage 5)."""

    title: str
    executive_summary: str
    methodology: str
    sections: list[ReportSection] = Field(default_factory=list)
    conclusion: str
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Session summary (generated after navigation completes)
# ---------------------------------------------------------------------------

class SessionSummary(BaseModel):
    """Summary of a single persona's session."""

    task_completed: bool
    total_steps: int
    key_struggles: list[str] = Field(default_factory=list)
    key_successes: list[str] = Field(default_factory=list)
    emotional_arc: list[EmotionalState] = Field(default_factory=list)
    summary: str
    overall_difficulty: str = Field(..., description="easy, moderate, or difficult")


# ---------------------------------------------------------------------------
# Stage 6: AI-Powered Fix Suggestions
# ---------------------------------------------------------------------------

class FixSuggestion(BaseModel):
    """A code fix suggestion for a UX issue."""

    fix_explanation: str = Field(..., description="Human-readable explanation of the fix")
    fix_code: str = Field(..., description="The actual code snippet to fix the issue")
    fix_language: FixLanguage = Field(..., description="Language of the fix: css, html, javascript, react, or general")
    alternative_approaches: list[str] = Field(default_factory=list, description="1-2 alternative ways to fix the issue")

    @field_validator("fix_explanation", "fix_code")
    @classmethod
    def _must_not_be_blank(cls, value: str) -> str:
        trimmed = value.strip()
        if not trimmed:
            raise ValueError("Field cannot be blank")
        return trimmed

    @field_validator("fix_language", mode="before")
    @classmethod
    def _normalize_fix_language(cls, value: str | FixLanguage) -> str | FixLanguage:
        if isinstance(value, FixLanguage):
            return value
        if not isinstance(value, str):
            return value

        normalized = value.strip().lower()
        aliases = {
            "js": "javascript",
            "ts": "javascript",
            "jsx": "react",
            "tsx": "react",
        }
        return aliases.get(normalized, normalized)


# ---------------------------------------------------------------------------
# Stage 2b: Agentic Navigation with Tool Use (Feature 1b)
# ---------------------------------------------------------------------------

class ToolCallRecord(BaseModel):
    """Record of a single tool call in the agentic navigation loop."""

    tool_name: str = Field(..., description="Name of the tool called")
    tool_input: dict[str, Any] = Field(default_factory=dict)
    tool_result: str = Field(default="", description="Result returned by tool execution")
    success: bool = Field(default=True)


class AgenticNavigationDecision(BaseModel):
    """Output of agentic navigation with tool use (multi-step reasoning)."""

    think_aloud: str = Field(..., description="Persona's inner monologue")
    tool_calls: list[ToolCallRecord] = Field(default_factory=list, description="Chain of tool calls made")
    final_action: NavigationAction = Field(..., description="Final resolved action after tool use")
    ux_issues: list[UXIssue] = Field(default_factory=list)
    confidence: float = Field(..., ge=0, le=1)
    task_progress: int = Field(..., ge=0, le=100)
    emotional_state: EmotionalState = Field(default=EmotionalState.neutral)
    reasoning: str = Field(default="", description="Internal reasoning chain")


# ---------------------------------------------------------------------------
# Stage 3b: Multi-Image Flow Analysis (Feature 1c)
# ---------------------------------------------------------------------------

class TransitionIssue(BaseModel):
    """Issue found in the transition between pages in a flow."""

    from_page: str = Field(..., description="URL of the source page")
    to_page: str = Field(..., description="URL of the destination page")
    description: str
    severity: Severity
    heuristic: str = Field(default="", description="Nielsen heuristic violated")
    recommendation: str = Field(default="")


class FlowAnalysis(BaseModel):
    """Output of multi-image flow analysis (Stage 3b)."""

    flow_name: str = Field(..., description="Name of the analyzed flow (e.g., 'checkout flow')")
    pages: list[str] = Field(default_factory=list, description="URLs in this flow sequence")
    consistency_score: int = Field(..., ge=1, le=10, description="Visual/UX consistency across pages")
    transition_issues: list[TransitionIssue] = Field(default_factory=list)
    information_loss: list[str] = Field(default_factory=list, description="Info lost between page transitions")
    strengths: list[str] = Field(default_factory=list)
    summary: str


# ---------------------------------------------------------------------------
# Accessibility Deep Audit (Feature 5)
# ---------------------------------------------------------------------------

class VisualAccessibilityIssue(BaseModel):
    """An accessibility issue detected via Opus vision that automated tools miss."""

    description: str
    wcag_criterion: str = Field(..., description="WCAG 2.1 criterion code (e.g., '1.4.3')")
    measured_value: str | None = Field(None, description="e.g., 'contrast ratio: 2.3:1'")
    required_value: str | None = Field(None, description="e.g., 'minimum 4.5:1'")
    element_description: str = Field(..., description="Description of the affected element")
    severity: Severity = Field(default=Severity.major)
    screenshot_region: dict[str, int] = Field(
        default_factory=dict, description="Bounding box {x, y, w, h}"
    )


class WCAGCriterionResult(BaseModel):
    """Pass/fail result for a single WCAG criterion."""

    criterion: str = Field(..., description="e.g., '1.1.1 Non-text Content'")
    level: str = Field(..., description="A, AA, or AAA")
    status: str = Field(..., description="pass, fail, or not_applicable")
    evidence: str = Field(default="", description="Evidence for the assessment")


class AccessibilityAudit(BaseModel):
    """Output of the deep accessibility audit using Opus vision."""

    page_url: str
    wcag_level: str = Field(default="AA", description="Target WCAG level: A, AA, or AAA")
    pass_count: int = Field(default=0)
    fail_count: int = Field(default=0)
    compliance_percentage: float = Field(default=0.0, ge=0, le=100)
    criteria: list[WCAGCriterionResult] = Field(default_factory=list)
    visual_issues: list[VisualAccessibilityIssue] = Field(default_factory=list)
    summary: str = Field(default="")


# ---------------------------------------------------------------------------
# Natural Language Test Builder (Feature 6)
# ---------------------------------------------------------------------------

class PlannedTask(BaseModel):
    """A task generated from natural language description."""

    description: str
    success_criteria: str = Field(default="", description="How to determine task completion")


class PlannedPersona(BaseModel):
    """A persona recommendation from the test planner."""

    name: str
    description: str
    template_id: str | None = Field(None, description="Match to existing template if available")


class StudyPlan(BaseModel):
    """Output of the natural language test builder."""

    tasks: list[PlannedTask] = Field(default_factory=list)
    personas: list[PlannedPersona] = Field(default_factory=list)
    device_recommendation: str = Field(default="desktop")
    estimated_duration_minutes: int = Field(default=5)
    rationale: str = Field(default="", description="Why these tasks and personas were chosen")
