"""Pydantic response models for all 5 LLM pipeline stages."""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------

class Severity(str, Enum):
    critical = "critical"
    major = "major"
    minor = "minor"
    enhancement = "enhancement"


class EmotionalState(str, Enum):
    confident = "confident"
    curious = "curious"
    neutral = "neutral"
    hesitant = "hesitant"
    confused = "confused"
    frustrated = "frustrated"
    satisfied = "satisfied"
    anxious = "anxious"


class ActionType(str, Enum):
    click = "click"
    type_text = "type"
    scroll = "scroll"
    navigate = "navigate"
    wait = "wait"
    go_back = "go_back"
    done = "done"
    give_up = "give_up"


# ---------------------------------------------------------------------------
# Stage 1: Persona Generation
# ---------------------------------------------------------------------------

class AccessibilityNeeds(BaseModel):
    screen_reader: bool = False
    low_vision: bool = False
    color_blind: bool = False
    motor_impairment: bool = False
    cognitive: bool = False
    description: str | None = None


class PersonaProfile(BaseModel):
    """Full persona profile generated by Opus."""

    name: str = Field(..., description="Full name of the persona")
    age: int = Field(..., ge=13, le=95)
    occupation: str
    emoji: str = Field(..., description="Single emoji avatar")
    short_description: str = Field(..., max_length=200)
    background: str = Field(..., description="2-3 sentence backstory")

    # Behavioral attributes (1-10 scale)
    tech_literacy: int = Field(..., ge=1, le=10)
    patience_level: int = Field(..., ge=1, le=10)
    reading_speed: int = Field(..., ge=1, le=10, description="1=skims, 10=reads every word")
    trust_level: int = Field(..., ge=1, le=10, description="1=very skeptical, 10=trusts everything")
    exploration_tendency: int = Field(..., ge=1, le=10, description="1=task-focused, 10=explores everything")

    # Context
    device_preference: str = Field(default="desktop", description="desktop, mobile, or tablet")
    frustration_triggers: list[str] = Field(default_factory=list)
    goals: list[str] = Field(default_factory=list)
    accessibility_needs: AccessibilityNeeds = Field(default_factory=AccessibilityNeeds)

    # Behavioral modifiers derived from attributes
    behavioral_notes: str = Field(
        default="",
        description="Generated behavioral notes for the navigation engine",
    )


# ---------------------------------------------------------------------------
# Stage 2: Navigation Decision-Making
# ---------------------------------------------------------------------------

class NavigationAction(BaseModel):
    """A single browser action to execute."""

    type: ActionType
    selector: str | None = Field(None, description="CSS selector for click/type")
    value: str | None = Field(None, description="Text to type, URL to navigate, scroll direction")
    description: str = Field(..., description="Human-readable description of the action")


class UXIssue(BaseModel):
    """A UX issue detected during navigation."""

    element: str = Field(..., description="The UI element involved")
    description: str
    severity: Severity
    heuristic: str = Field(..., description="Nielsen heuristic violated")
    wcag_criterion: str | None = Field(None, description="WCAG criterion if applicable")
    recommendation: str


class NavigationDecision(BaseModel):
    """Output of the navigation LLM call (Stage 2)."""

    think_aloud: str = Field(..., description="Persona's inner monologue / think-aloud")
    action: NavigationAction
    ux_issues: list[UXIssue] = Field(default_factory=list)
    confidence: float = Field(..., ge=0, le=1, description="Confidence in the chosen action")
    task_progress: int = Field(
        ..., ge=0, le=100, description="Estimated task completion percentage"
    )
    emotional_state: EmotionalState = Field(default=EmotionalState.neutral)
    reasoning: str = Field(default="", description="Internal reasoning for the action choice")


# ---------------------------------------------------------------------------
# Stage 3: Screenshot UX Analysis (post-session)
# ---------------------------------------------------------------------------

class PageAssessment(BaseModel):
    """Assessment scores for a single page screenshot."""

    visual_clarity: int = Field(..., ge=1, le=10)
    information_hierarchy: int = Field(..., ge=1, le=10)
    action_clarity: int = Field(..., ge=1, le=10)
    error_handling: int = Field(..., ge=1, le=10)
    accessibility: int = Field(..., ge=1, le=10)
    overall: int = Field(..., ge=1, le=10)


class ScreenshotAnalysis(BaseModel):
    """Output of the screenshot analysis LLM call (Stage 3)."""

    page_url: str
    page_title: str
    assessment: PageAssessment
    issues: list[UXIssue] = Field(default_factory=list)
    strengths: list[str] = Field(default_factory=list)
    summary: str


# ---------------------------------------------------------------------------
# Stage 4: Cross-Persona Insight Synthesis
# ---------------------------------------------------------------------------

class StrugglePoint(BaseModel):
    """A point in the flow where personas struggled."""

    page_url: str
    element: str | None = None
    description: str
    personas_affected: list[str] = Field(default_factory=list)
    severity: Severity


class Recommendation(BaseModel):
    """A prioritized recommendation."""

    rank: int
    title: str
    description: str
    impact: str = Field(..., description="high, medium, or low")
    effort: str = Field(..., description="high, medium, or low")
    personas_helped: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)


class InsightItem(BaseModel):
    """A single insight from synthesis."""

    type: str = Field(
        ..., description="universal, persona_specific, comparative, or recommendation"
    )
    title: str
    description: str
    severity: Severity
    personas_affected: list[str] = Field(default_factory=list)
    evidence: list[str] = Field(default_factory=list)


class StudySynthesis(BaseModel):
    """Output of the cross-persona synthesis LLM call (Stage 4)."""

    executive_summary: str
    overall_ux_score: int = Field(..., ge=0, le=100)
    universal_issues: list[InsightItem] = Field(default_factory=list)
    persona_specific_issues: list[InsightItem] = Field(default_factory=list)
    comparative_insights: list[InsightItem] = Field(default_factory=list)
    struggle_points: list[StrugglePoint] = Field(default_factory=list)
    recommendations: list[Recommendation] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Stage 5: Report Generation
# ---------------------------------------------------------------------------

class ReportSection(BaseModel):
    """A section of the generated report."""

    heading: str
    content: str = Field(..., description="Markdown content")
    subsections: list[ReportSection] = Field(default_factory=list)


class ReportContent(BaseModel):
    """Output of the report generation LLM call (Stage 5)."""

    title: str
    executive_summary: str
    methodology: str
    sections: list[ReportSection] = Field(default_factory=list)
    conclusion: str
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Session summary (generated after navigation completes)
# ---------------------------------------------------------------------------

class SessionSummary(BaseModel):
    """Summary of a single persona's session."""

    task_completed: bool
    total_steps: int
    key_struggles: list[str] = Field(default_factory=list)
    key_successes: list[str] = Field(default_factory=list)
    emotional_arc: list[EmotionalState] = Field(default_factory=list)
    summary: str
    overall_difficulty: str = Field(..., description="easy, moderate, or difficult")


# ---------------------------------------------------------------------------
# Stage 6: AI-Powered Fix Suggestions
# ---------------------------------------------------------------------------

class FixSuggestion(BaseModel):
    """A code fix suggestion for a UX issue."""

    fix_explanation: str = Field(..., description="Human-readable explanation of the fix")
    fix_code: str = Field(..., description="The actual code snippet to fix the issue")
    fix_language: str = Field(..., description="Language of the fix: css, html, javascript, react, or general")
    alternative_approaches: list[str] = Field(default_factory=list, description="1-2 alternative ways to fix the issue")
